### ISSUE TITLE
This is more like a question than an issue

### ISSUE THREAD

**Issue by nalanirojas25** [react-puzzle-games/15-puzzle#43]
Hello, 

I'm creating a race car game and researching different ways in which the timers are implemented in the games created in react so I wanted to know what made you use setInterval vs requestAnimationFrame?

**Comment by ovidiubute** [comment]
That's a good question, requestAnimationFrame is likely to get you better performance vs. setInterval because the browser will try and schedule it before the next paint whereas there are no guarantees about when a callback scheduled with setInterval will be called. If you have a racing game I'd recommend using requestAnimationFrame because of this.

In my 15 puzzle game however there aren't a lot of animations (unlike a racing game I'd imagine) so the performance gain I think wouldn't be super obvious.
